<!DOCTYPE html>
<html lang="fr" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link href="https://fonts.googleapis.com/css?family=ZCOOL+QingKe+HuangYou" rel="stylesheet">
    <link rel="stylesheet" href="css/game/normalize.css">
    <link rel="stylesheet" href="css/game/style.css">
    <link rel="stylesheet" href="css/normalize.css">
    <link rel="stylesheet" href="css/style.css">

    <script
      src="https://code.jquery.com/jquery-3.3.1.js"
      integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
      crossorigin="anonymous">
    </script>

    <script type="text/javascript" src="js/game/script.js"></script>
    <script type="text/javascript" src="js/game/main.js"></script>

    <script type="text/javascript" src="js/utilities.js"></script>
    <script type="text/javascript" src="js/script.js"></script>
    <script type="text/javascript" src="js/main.js"></script>

    <title>Jump</title>
  </head>
  <body>
    <main style="color: #000;">
      <h2 style="text-align: center; font-weight: normal; margin-bottom: 2rem;">Jump</h2>
      <canvas id="canvas_1" width="480" height="320"></canvas>
      <canvas id="canvas_2" width="480" height="320"></canvas>
    </main>
  </body>
</html>
