<!DOCTYPE html>
<html lang="fr" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link href="https://fonts.googleapis.com/css?family=ZCOOL+QingKe+HuangYou" rel="stylesheet">
    <link rel="stylesheet" href="css/normalize.css">
    <link type="text/css" rel="stylesheet" href="css/style.css">
    <script
    src="https://code.jquery.com/jquery-3.3.1.js"
    integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
    crossorigin="anonymous"></script>
    <script type="text/javascript" src="js/utilities.js"></script>
    <script type="text/javascript" src="js/script.js"></script>
    <script type="text/javascript" src="js/main.js"></script>
    <title>Logged</title>
  </head>
  <body id="logged">
    <main class="no_signin_link">
      <div style="text-align: center; padding: 5rem;">
        <p>Vous êtes connecté.</p>
        <p>Vous serez redirigez vers la page d'accueil dans 3 secondes.</p>
        <script> setTimeout(function() { window.location = "index.php"; }, 3000); </script>
      </div>

    </main>
  </body>
</html>
