<!DOCTYPE html>
<html lang="fr" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link href="https://fonts.googleapis.com/css?family=ZCOOL+QingKe+HuangYou" rel="stylesheet">
    <link rel="stylesheet" href="css/normalize.css">
    <link type="text/css" rel="stylesheet" href="css/style.css">
    <script
      src="https://code.jquery.com/jquery-3.3.1.js"
      integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
      crossorigin="anonymous">
    </script>
    <script type="text/javascript" src="js/utilities.js"></script>
    <script type="text/javascript" src="js/script.js"></script>
    <script type="text/javascript" src="js/main.js"></script>
    <title>Post</title>
  </head>
  <body id="post">

    <main>
      <section id="s_post">
        <?php include 'src/post.php'; ?>
      </section><!--
      --><aside>

      </aside>
      <div id="show_comms">
        <button type="button" name="button">Afficher les commentaires</button>
      </div>


      <section id="s_comms" class="hide">
        <h2>nb_comms sur "titre_post"</h2>
        <?php if ($_SESSION['user_data']): ?>
          <button id="add_comm" type="button" name="button">Ajouter un commentaire</button>
        <?php else: ?>
          <h3 style="text-align: center;"><a href="sign-in.php">S'inscrire pour poster votre commentaire</a></h3>
        <?php  endif; ?>
      </section>

    </main>
  </body>
</html>
