<!DOCTYPE html>
<html lang="fr" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link href="https://fonts.googleapis.com/css?family=ZCOOL+QingKe+HuangYou" rel="stylesheet">
    <link rel="stylesheet" href="css/normalize.css">
    <link type="text/css" rel="stylesheet" href="css/style.css">
    <script
    src="https://code.jquery.com/jquery-3.3.1.js"
    integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
    crossorigin="anonymous"></script>
    <script type="text/javascript" src="js/utilities.js"></script>
    <script type="text/javascript" src="js/script.js"></script>
    <script type="text/javascript" src="js/main.js"></script>
    <title>Update</title>
  </head>
  <body>
    <main>
      <section id="test">
        <div style="margin-bottom: 4rem;">
          <form action="./update.php" method="post" enctype="multipart/form-data">
            Image :<input type="file" name="test" accept="image/*">
            Id billet :<input type="number" name="id">
            <button type="submit" name="button">Envoyer</button>
          </form>
        </div>
        <div>
          <form action="./update.php" method="post" enctype="multipart/form-data">
            Champ: : <input type="text" name="champ">
            Pseudo : <input type="text" name="pseudo">
            Password : <input type="text" name="pwd">
            Image :<input type="file" name="avatar" accept="image/*">
            <button type="submit" name="button">Envoyer</button>
          </form>
        </div>
        <p><?php echo var_dump($_POST); ?></p>
        <?php foreach ($_POST as $key):?>
          <p><?= var_dump($key); ?></p>
        <?php endforeach; ?>
      </section><!--
      --><aside>

      </aside>
    </main>

  </body>
</html>
