<!DOCTYPE html>
<html lang="fr" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link href="https://fonts.googleapis.com/css?family=ZCOOL+QingKe+HuangYou" rel="stylesheet">
    <link rel="stylesheet" href="css/normalize.css">
    <link type="text/css" rel="stylesheet" href="css/style.css">
    <script
    src="https://code.jquery.com/jquery-3.3.1.js"
    integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
    crossorigin="anonymous"></script>
    <script type="text/javascript" src="js/utilities.js"></script>
    <script type="text/javascript" src="js/script.js"></script>
    <script type="text/javascript" src="js/main.js"></script>
    <title>Update Billet</title>
  </head>
  <body>
    <form action="./test.php" method="post" enctype="multipart/form-data">
      <input type="file" name="test" accept="image/*">
      <input type="number" name="id">
      <button type="submit" name="button">Envoyer</button>
    </form>
    <section id="test">
      <p>test</p>
    </section><!--
    --><aside>
      <?php include './src/aside.php'; ?>
    </aside>
  </body>
</html>
