<?php
include './src/repository/select-all.php';
 ?>
<!DOCTYPE html>
<html lang="fr" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link href="https://fonts.googleapis.com/css?family=ZCOOL+QingKe+HuangYou" rel="stylesheet">
    <link rel="stylesheet" href="css/normalize.css">
    <link type="text/css" rel="stylesheet" href="css/style.css">
    <script
    src="https://code.jquery.com/jquery-3.3.1.js"
    integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
    crossorigin="anonymous"></script>
    <script type="text/javascript" src="js/utilities.js"></script>
    <script type="text/javascript" src="js/script.js"></script>
    <script type="text/javascript" src="js/main.js"></script>
    <script type="text/javascript" src="admin/script.js"></script>
    <script type="text/javascript" src="admin/main.js"></script>
    <title>Administration</title>
  </head>
  <body id="administration">
    <main>
      <section class="sec_admin">
        <h2>Billets</h2>
        <select name="billet" style="margin: 0 auto; display: block; font-size: 2em;">

        </select>
        <form action="admin/repository/update_post.php" method="post" enctype="multipart/form-data">
          <fieldset id="fd" style="border: none;">
            <ul>

            </ul>
          </fieldset>
        </form>
        <?php session_start(); ?>
        <?php if(isset($_SESSION['billet_updated_message'])): ?>
          <p id="p" style="text-align: center;"><?= $_SESSION['billet_updated_message']; unset($_SESSION['billet_updated_message']); ?></p>
          <script type="text/javascript">
          window.setTimeout(function () {
            $('#p').html('');;
          }, 3000);
          </script>
        <?php endif; ?>
      </section>

      <section class="sec_admin">
        <h2>Utilisateurs</h2>
        <select name="user" style="margin: 0 auto; display: block; font-size: 2em;">

        </select>
        <form action="admin/repository/update_user.php" method="post" enctype="multipart/form-data">
          <fieldset id="fd_user" style="border: none;">
            <ul>

            </ul>
          </fieldset>
        </form>
      </section>
    </main>
  </body>
</html>
