<?php
include './src/repository/select-all.php';
 ?>
<!DOCTYPE html>
<html lang="fr" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link href="https://fonts.googleapis.com/css?family=ZCOOL+QingKe+HuangYou" rel="stylesheet">
    <link rel="stylesheet" href="css/normalize.css">
    <link type="text/css" rel="stylesheet" href="css/style.css">
    <script
    src="https://code.jquery.com/jquery-3.3.1.js"
    integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
    crossorigin="anonymous"></script>
    <script type="text/javascript" src="js/utilities.js"></script>
    <script type="text/javascript" src="js/script.js"></script>
    <script type="text/javascript" src="js/main.js"></script>
    <script type="text/javascript" src="admin/script.js"></script>
    <script type="text/javascript" src="admin/main.js"></script>
    <title>Administration</title>
  </head>
  <body id="administration">
    <h1 style="text-align: center; color: #fff; width: 100%; margin: 0;">Update Data</h1>
    <main>
      <section class="sec_admin">
        <h2>Billets</h2>
        <select name="billet" style="margin: 0 auto; display: block; font-size: 2em;">

        </select>
        <form class="" action="index.html" method="post">
          <fieldset id="fd" style="border: none;">
            <ul>

            </ul>
          </fieldset>
        </form>


      </section>
      
      <section class="sec_admin">
        <h2>Utilisateurs</h2>
        <select name="user" style="margin: 0 auto; display: block; font-size: 2em;">

        </select>
        <form class="" action="index.html" method="post">
          <fieldset id="fd_user" style="border: none;">
            <ul>

            </ul>
          </fieldset>
        </form>
      </section>

      <section class="sec_admin">
        <h2>Categorie</h2>
        <select name="cat" style="margin: 0 auto; display: block; font-size: 2em;">

        </select>
        <form class="" action="index.html" method="post">
          <fieldset>
            <ul>
              <!--select name="cat">
                <?php foreach ($cat_results as $key): ?>
                  <option value="<?= $key['id_categorie']; ?>"><?= $key['nom']; ?></option>
                <?php endforeach; ?>
              </select-->
              <li><input type="text" name="" value=""></li>
              <li><input type="text" name="" value=""></li>
              <li><textarea name="name" rows="6" cols="30"></textarea></li>
              <li><input type="file" name="" value=""></li>
            </ul>
          </fieldset>
        </form>
      </section>
    </main>
  </body>
</html>
